CREATE TYPE project_role AS ENUM ('owner', 'participant');

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ix_users_login ON users (login);

CREATE TABLE projects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    description text,
    owner_id integer NOT NULL REFERENCES users (id),
    total_size_bytes bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_projects_owner_id ON projects (owner_id);

CREATE TABLE project_access (
    project_id integer NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role project_role NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    s3_key varchar(1024) NOT NULL,
    filename varchar(255) NOT NULL,
    content_type varchar(255) NOT NULL,
    size_bytes bigint NOT NULL,
    uploaded_by_id integer NOT NULL REFERENCES users (id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_documents_project_id ON documents (project_id);
CREATE INDEX ix_documents_uploaded_by_id ON documents (uploaded_by_id);
CREATE UNIQUE INDEX uq_documents_s3_key ON documents (s3_key);
